# Generated by Django 2.0.2 on 2021-12-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coats', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
