# Generated by Django 2.0.2 on 2021-12-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coats', '0004_auto_20211212_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
