# Generated by Django 2.0.2 on 2021-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coats', '0005_auto_20211212_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
